djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoProject import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('calculate.geometry/', include('geometry.urls')),
    path('zodiac/', include('zodiac.urls')),
    path('zodiac_db/', include('zodiacWithDB.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geometry/urls.py
from django.urls import path
from . import views

app_name = 'geometry'

urlpatterns = [
    path('rectangle/<int:width>/<int:height>/', views.get_rectangle_area, name='rectangle_area'),
    path('square/<int:width>/', views.get_square_area, name='square_area'),
    path('circle/<int:radius>/', views.get_circle_area, name='circle_area'),
]

zodiac/urls.py
from django.urls import path
from .views import show_all_signs, show_sign

app_name = 'zodiac'
urlpatterns = [
    path('all/', show_all_signs, name='show_all_signs'),
    path('<str:sign_name>/', show_sign, name='show_sign'),
]

zodiacWithDB/urls.py
from django.urls import path
from . import views

app_name = 'zodiacWithDB'

urlpatterns = [
    path('', views.zodiac_list, name='zodiac_list'),
    path('<str:sign_id>/', views.zodiac_detail, name='zodiac_detail'),
]

zodiac/models.py
from django.db import models

# Create your models here.

zodiacWithDB/models.py
from django.db import models

class ZodiacSign(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='zodiac_images/')

    def __str__(self):
        return self.name

djangoProject/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

geometry/views.py
from django.shortcuts import render
from django.http import HttpResponse
import math

#прямоугольник
def get_rectangle_area(request, width, height):
    area = width * height
    return HttpResponse(f"Площадь прямоугольника: {area}")

#квадрат
def get_square_area(request, width):
    area = width * width
    return HttpResponse(f"Площадь квадрата: {area}")

#круг
def get_circle_area(request, radius):
    area = math.pi * (radius ** 2)
    return HttpResponse(f"Площадь круга: {area:.2f}")

zodiac/views.py
from dbm import error
from lib2to3.fixes.fix_input import context

from django.shortcuts import render

ZODIAC_SIGNS = [
    {'name': 'Овен', 'description': 'Овен — это знак энергии, стремления и активности. Люди, рожденные под этим знаком, известны своим упорством и смелостью. Они любят быть в центре внимания и часто берут на себя лидерство.', 'image': 'images/aries.jpg'},
    {'name': 'Телец', 'description': 'Телец — это знак стабильности и упорства. Люди, рожденные под этим знаком, ценят комфорт и материальные блага. Они практичны, реалистичны и способны стойко переносить трудности.', 'image': 'images/taurus.jpg'},
    {'name': 'Близнецы', 'description': 'Близнецы — это знак общения и любознательности. Люди, рожденные под этим знаком, обладают быстрым умом и остроумием. Они обожают общаться и исследовать новые идеи.', 'image': 'images/gemini.jpg'},
    {'name': 'Рак', 'description': 'Рак — это знак эмоций и чувствительности. Люди, рожденные под этим знаком, часто заботливы и защитны по отношению к своим близким. Они ценят домашний уют и семейные традиции.', 'image': 'images/cancer.jpg'},
    {'name': 'Лев', 'description': 'Лев — это знак творчества и самовыражения. Люди, рожденные под этим знаком, обладают харизмой и уверенность в себе. Они любят быть в центре внимания и стремятся вдохновлять других.', 'image': 'images/leo.jpg'},
    {'name': 'Дева', 'description': 'Дева — это знак анализа и внимания к деталям. Люди, рожденные под этим знаком, практичны и трудолюбивы. Они стремятся к совершенству и могут быть критичными как к себе, так и к другим.', 'image': 'images/virgo.jpg'},
    {'name': 'Весы', 'description': 'Весы — это знак гармонии и справедливости. Люди, рожденные под этим знаком, ценят красоту и искусство. Они стремятся к равновесию и часто играют роль миротворцев.', 'image': 'images/libra.jpg'},
    {'name': 'Скорпион', 'description': 'Скорпион — это знак глубины и интенсивности. Люди, рожденные под этим знаком, эмоциональны и страстны. Они часто интересуются скрытыми истинами и мистикой.', 'image': 'images/scorpio.jpg'},
    {'name': 'Стрелец', 'description': 'Стрелец — это знак приключений и оптимизма. Люди, рожденные под этим знаком, стремятся к свободе и исследованию. Они открыты для новых идей и имеют широкий кругозор.', 'image': 'images/sagittarius.jpg'},
    {'name': 'Козерог', 'description': 'Козерог — это знак дисциплины и амбициозности. Люди, рожденные под этим знаком, трудолюбивы и нацелены на достижение своих целей. Они практичны и реалистичны.', 'image': 'images/capricorn.jpg'},
    {'name': 'Водолей', 'description': 'Водолей — это знак оригинальности и независимости. Люди, рожденные под этим знаком, стремятся к переменам и прогрессу. Они часто являются новаторами и обладают уникальным взглядом на жизнь.', 'image': 'images/aquarius.jpg'},
    {'name': 'Рыбы', 'description': 'Рыбы — это знак интуиции и чувствительности. Люди, рожденные под этим знаком, творческие и мечтательные. Они обладают глубокой эмпатией и часто могут понимать чувства других.', 'image': 'images/pisces.jpg'},
]

def show_all_signs(request):
    return render(request, 'zodiac/show_all_signs.html', {'signs': ZODIAC_SIGNS})

def show_sign(request, sign_name):
    # Находим знак по имени
    sign = next((s for s in ZODIAC_SIGNS if s['name'] == sign_name), None)
    if sign is None:
        context = {"error": "error"}
        return render(request, 'zodiac/show_sign.html', context)

    context = {'sign': sign,"error": ""}
    return render(request, 'zodiac/show_sign.html', context)

zodiacWithDB/views.py
from django.shortcuts import render, get_object_or_404
from .models import ZodiacSign


#список
def zodiac_list(request):
    signs = ZodiacSign.objects.all()
    return render(request, 'zodiacWithDB/zodiac_list.html', {'signs': signs})


#конкретный знак
def zodiac_detail(request, sign_id):
    #если sign_id не может быть преобразован в int - ValueError и перекинет в 404
    #если не найдена запись по id - DoesNotExist и перекинет в 404
    try:
        sign_id = int(sign_id)
        sign = ZodiacSign.objects.get(id=sign_id)
        return render(request, 'zodiacWithDB/zodiac_detail.html', {'sign': sign})
    except (ZodiacSign.DoesNotExist, ValueError):
        return render(request, 'zodiacWithDB/404.html', status=404)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
</head>
<body>
    <h1>Веб-программирование</h1>
    <h2><a href="/admin/">Админка</a></h2>
    <h2>Геометрия</h2>
        <ul>
            <li><a href="{% url 'geometry:rectangle_area' width=5 height=10 %}">Площадь прямоугольника 5x10</a></li>
            <li><a href="{% url 'geometry:square_area' width=4 %}">Площадь квадрата 4x4</a></li>
            <li><a href="{% url 'geometry:circle_area' radius=7 %}">Площадь круга с радиусом 7</a></li>
        </ul> 
    <p><a href="{% url 'zodiac:show_all_signs' %}">Знаки зодиака</a></p>  
    <p><a href="{% url 'zodiacWithDB:zodiac_list' %}">Знаки зодиака с БД</a></p>
</body>
</html>
</body>
</html>

templates/zodiacWithDB/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Знаки Зодиака{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'zodiacWithDB/css/styles.css' %}">
</head>
<body>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/zodiacWithDB/zodiac_detail.html
{% extends "zodiacWithDB/base.html" %}
{% load static %}

{% block title %}{{ sign.name }}{% endblock %}

{% block content %}
    <h1 class="text-center">{{ sign.name }}</h1>
    <div class="text-center">
        <img src="{{ sign.image.url }}" class="img-fluid" alt="{{ sign.name }}">
    </div>
    <p class="mt-3">{{ sign.description }}</p>
    <a href="{% url 'zodiacWithDB:zodiac_list' %}" class="btn btn-secondary">Назад к списку</a>

    {% if error_message %}
        <div class="alert alert-danger mt-4">
            {{ error_message }}
        </div>
    {% endif %}
{% endblock %}

templates/zodiacWithDB/zodiac_list.html
{% extends "zodiacWithDB/base.html" %}
{% load static %}

{% block title %}Список Знаков Зодиака{% endblock %}

{% block content %}
    <h1 class="text-center">Список Знаков Зодиака</h1>
     <form method="GET" action="{% url 'zodiacWithDB:zodiac_list' %}" class="mb-4">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Поиск по знаку" value="{{ request.GET.q }}">
            <button class="btn btn-outline-secondary" type="submit">Найти</button>
        </div>
    </form>
    <div class="row">
        {% for sign in signs %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ sign.image.url }}" class="card-img-top" alt="{{ sign.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ sign.name }}</h5>
                        <a href="{% url 'zodiacWithDB:zodiac_detail' sign.id %}" class="btn btn-primary">Подробнее</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

zodiac/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

zodiac/templates/zodiac/show_all_signs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Все знаки зодиака{% endblock %}

{% block content %}
<h2>Список знаков зодиака</h2>
<ul>
    {% for sign in signs %}
        <li><a href="{% url 'zodiac:show_sign' sign.name %}">{{ sign.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

zodiac/templates/zodiac/show_sign.html
{% extends 'base.html'%}
{% load static %}

{% block title %}{{ sign.name }}{% endblock %}

{% block content %}
    {% if error == ""%}
        <h2>{{ sign.name }}</h2>
        <img src="{% static sign.image %}" alt="{{ sign.name }}" style="width: 500px; height: auto;">
        <p>{{ sign.description }}</p>
    {% else %}
     <h2>Нет знака</h2>
    {% endif %}
{% endblock %}